/**
 * Article data loader for RRM Research Library.
 * Reads from articles.json (generated by fetch-data.mjs from D1 worker).
 */

export interface Article {
  id: string;
  slug: string;
  title: string;
  authors: string;
  shortCitation: string;
  year: number | null;
  abstract: string;
  journal: string;
  journalAbbv: string;
  doi: string;
  pmid: string;
  sourceUrl: string;
  datePublished: string;
  volume: string;
  issue: string;
  pages: string;
  keywords: string;
  apaCitation: string;
  vancouverCitation: string;
  mlaCitation: string;
  topics: string[];
  searchTerms: string[];
  enrichmentStatus: string;
  identifiers: string[];
  isOpenAccess: boolean;
  isCopyrighted: boolean;
  oaType: string;
  license: string;
  oaUrl: string;
  accessLevel: 'open' | 'free' | 'restricted';
  sentiment: string;
  rrmRelevance: string;
  domain: string;
  lastModified: string;
  dateAddedToLibrary: string;
}

export async function fetchAllArticles(): Promise<Article[]> {
  try {
    const cached = await import('../data/articles.json');
    const articles = (cached.default || cached) as Article[];
    if (articles.length > 0) {
      console.log(`[airtable] Loaded ${articles.length} articles from cache`);
      return articles;
    }
    throw new Error('articles.json is empty');
  } catch (err: any) {
    if (err?.code === 'ERR_MODULE_NOT_FOUND') {
      throw new Error('articles.json not found. Run: WORKER_AUTH_TOKEN=xxx npm run fetch-data');
    }
    throw new Error(`Failed to load articles.json: ${err?.message}`);
  }
}

/**
 * Find related articles using weighted multi-signal scoring:
 *   topics (×3) + search terms (×1) + same journal (×2)
 * Tiebreaker: more recent articles rank higher.
 */
export function getRelatedArticles(
  article: Article,
  allArticles: Article[],
  limit = 4
): Article[] {
  if (article.topics.length === 0 && article.searchTerms.length === 0) return [];

  const topicSet = new Set(article.topics);
  const termSet = new Set(article.searchTerms.map(t => t.toLowerCase()));
  const journal = article.journal.toLowerCase();

  const scored = allArticles
    .filter(a => a.id !== article.id)
    .map(a => {
      const topicOverlap = a.topics.filter(t => topicSet.has(t)).length;
      const lowerTerms = a.searchTerms.map(t => t.toLowerCase());
      const termOverlap = lowerTerms.filter(t => termSet.has(t)).length;
      const journalMatch = journal && a.journal.toLowerCase() === journal ? 1 : 0;
      return {
        article: a,
        score: (topicOverlap * 3) + (termOverlap * 1) + (journalMatch * 2),
      };
    })
    .filter(s => s.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      // Tiebreaker: prefer more recent
      const da = a.article.datePublished || '';
      const db = b.article.datePublished || '';
      return db.localeCompare(da);
    });

  return scored.slice(0, limit).map(s => s.article);
}
