#!/usr/bin/env python3
"""Write v2 drafts for the 11 Part-assigned v2-empty rows."""
import json, urllib.request, subprocess
from datetime import datetime, timezone

TOKEN = subprocess.run(["gcloud","auth","application-default","print-access-token"], capture_output=True, text=True).stdout.strip()
SHEET_ID = "1JNFrImZyp6O17NqNKsdwbvz5tF6K56yXXZ4uxzT2zvk"
TS = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# 11 drafts: (row, v2_text, v2_html, refs_cited, notes)
DRAFTS = {
275: {
"v2": """Restorative, as a principle in medicine, denotes a therapeutic approach whose explicit goal is to repair, heal, or optimize the natural function of an organ system rather than to suppress its symptoms, replace its function with a synthetic substitute, or bypass its biology with a procedural workaround.[1] In restorative reproductive medicine, this principle organizes clinical decision-making: clinicians identify the underlying conditions causing infertility, recurrent pregnancy loss, abnormal bleeding, or cycle disorder, and treat those conditions directly with the aim of restoring the patient's intrinsic reproductive function.

The restorative orientation contrasts with three other patterns common in mainstream reproductive medicine. Suppressive therapies (such as hormonal contraception used to mask cycle symptoms) mute the body's signals without addressing the underlying pathology. Replacement therapies (such as exogenous gonadotropins administered without correcting the upstream defect) substitute synthetic hormonal input for endogenous regulation. Bypass therapies (such as in vitro fertilization performed without diagnosing the cause of infertility) circumvent the affected biology rather than repairing it.

The restorative principle does not preclude pharmacotherapy, surgery, or assisted technologies. It requires that any intervention be selected with reference to a diagnosed underlying cause and an explicit restorative goal. Treatments that meet this standard are restorative even when they involve drugs or surgery; treatments that do not meet this standard are suppressive, replacement, or bypass even when they appear conservative.""",
"v2_html": """<p><strong>Restorative, as a principle in medicine, denotes a therapeutic approach whose explicit goal is to repair, heal, or optimize the natural function of an organ system rather than to suppress its symptoms, replace its function with a synthetic substitute, or bypass its biology with a procedural workaround.</strong><sup class="cite-ref"><a href="#ref-1">1</a></sup> In <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a>, this principle organizes clinical decision-making: clinicians identify the underlying conditions causing infertility, recurrent pregnancy loss, abnormal bleeding, or cycle disorder, and treat those conditions directly with the aim of restoring the patient's intrinsic reproductive function.</p><p>The restorative orientation contrasts with three other patterns common in mainstream reproductive medicine. <strong>Suppressive</strong> therapies (such as hormonal contraception used to mask cycle symptoms) mute the body's signals without addressing the underlying pathology. <strong>Replacement</strong> therapies (such as exogenous gonadotropins administered without correcting the upstream defect) substitute synthetic hormonal input for endogenous regulation. <strong>Bypass</strong> therapies (such as <a href="#ivf" class="gloss-xref">in vitro fertilization</a> performed without diagnosing the cause of infertility) circumvent the affected biology rather than repairing it.</p><p>The restorative principle does not preclude pharmacotherapy, surgery, or assisted technologies. It requires that any intervention be selected with reference to a diagnosed underlying cause and an explicit restorative goal. Treatments that meet this standard are restorative even when they involve drugs or surgery; treatments that do not meet this standard are suppressive, replacement, or bypass even when they appear conservative.</p>"""
},
330: {
"v2": """The Vaginal Discharge Recording System (VDRS) is the standardized observation and coding framework that underlies the Creighton Model FertilityCare System chart.[78] Developed by Dr. Thomas Hilgers at the Pope Paul VI Institute, the VDRS prescribes how a woman observes any discharge present at the vulva at each bathroom visit, and how each observation is translated into a single structured chart entry combining mucus type, stretch length, color, and sensation.

The VDRS is rule-based rather than impressionistic. Every observation slot has a defined coding outcome regardless of the user's interpretation, which makes Creighton Model charts comparable across users, instructors, and clinical reviewers. The structured vocabulary supports both the educational function of fertility awareness (helping a user recognize fertility-related biomarkers in her own cycle) and the diagnostic function of NaProTechnology (giving a clinician a standardized record that can be read alongside hormonal and ultrasound data).

The VDRS is the operational distinction between charting a sensation and recording a biomarker. By imposing a vocabulary, it converts a subjective daily observation into a clinically usable data stream. Other fertility awareness-based methods use different observation systems suited to their own biomarker hierarchies; what is specific to the Creighton Model is the use of the VDRS as the complete observation framework, with no parallel symptom diary or interpretive notes added by the user.""",
"v2_html": """<p><strong>The Vaginal Discharge Recording System (VDRS) is the standardized observation and coding framework that underlies the <a href="#creighton-model" class="gloss-xref">Creighton Model FertilityCare System</a> chart.</strong><sup class="cite-ref"><a href="#ref-78">78</a></sup> Developed by Dr. Thomas Hilgers at the Pope Paul VI Institute, the VDRS prescribes how a woman observes any discharge present at the vulva at each bathroom visit, and how each observation is translated into a single structured chart entry combining mucus type, stretch length, color, and sensation.</p><p>The VDRS is rule-based rather than impressionistic. Every observation slot has a defined coding outcome regardless of the user's interpretation, which makes Creighton Model charts comparable across users, instructors, and clinical reviewers. The structured vocabulary supports both the educational function of <a href="#fertility-awareness-based-methods" class="gloss-xref">fertility awareness</a> (helping a user recognize fertility-related biomarkers in her own cycle) and the diagnostic function of <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> (giving a clinician a standardized record that can be read alongside hormonal and ultrasound data).</p><p>The VDRS is the operational distinction between charting a sensation and recording a biomarker. By imposing a vocabulary, it converts a subjective daily observation into a clinically usable data stream. Other fertility awareness-based methods use different observation systems suited to their own biomarker hierarchies; what is specific to the Creighton Model is the use of the VDRS as the complete observation framework, with no parallel symptom diary or interpretive notes added by the user.</p>"""
},
273: {
"v2": """The Reproductive Health Research Institute (RHRI) is the research and clinical-training organization that develops and disseminates the FEMM (Fertility Education and Medical Management) program. Founded by Dr. Pilar Vigil, a Chilean reproductive endocrinologist with academic and clinical leadership in Latin America, RHRI focuses on integrating the menstrual cycle as a clinical vital sign into women's healthcare and on identifying chronic anovulation as a marker of long-term metabolic and cardiovascular risk.

RHRI's curriculum addresses both lay women, through FEMM cycle-tracking education, and clinicians, through professional training in cycle-based diagnostic and treatment approaches. Its work emphasizes that polycystic ovary syndrome, recurrent anovulation, and unexplained infertility are not isolated reproductive conditions but markers of broader endocrine and metabolic dysregulation that warrant systematic clinical attention.

RHRI is one of several institutions in the restorative reproductive medicine ecosystem; it is distinct from the International Institute for Restorative Reproductive Medicine, the Pope Paul VI Institute, and FertilityCare Centers of America, though there is overlap in member clinicians and shared evidence base. RHRI's distinctive contribution is the FEMM medical management program, which extends cycle-based assessment into chronic-disease prevention and reproductive endocrinology.""",
"v2_html": """<p><strong>The Reproductive Health Research Institute (RHRI) is the research and clinical-training organization that develops and disseminates the FEMM (Fertility Education and Medical Management) program.</strong> Founded by Dr. Pilar Vigil, a Chilean reproductive endocrinologist with academic and clinical leadership in Latin America, RHRI focuses on integrating the menstrual cycle as a clinical vital sign into women's healthcare and on identifying chronic <a href="#anovulation" class="gloss-xref">anovulation</a> as a marker of long-term metabolic and cardiovascular risk.</p><p>RHRI's curriculum addresses both lay women, through FEMM cycle-tracking education, and clinicians, through professional training in cycle-based diagnostic and treatment approaches. Its work emphasizes that <a href="#pcos" class="gloss-xref">polycystic ovary syndrome</a>, recurrent anovulation, and unexplained infertility are not isolated reproductive conditions but markers of broader endocrine and metabolic dysregulation that warrant systematic clinical attention.</p><p>RHRI is one of several institutions in the <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a> ecosystem; it is distinct from the <a href="#iirrm" class="gloss-xref">International Institute for Restorative Reproductive Medicine</a>, the Pope Paul VI Institute, and FertilityCare Centers of America, though there is overlap in member clinicians and shared evidence base. RHRI's distinctive contribution is the FEMM medical management program, which extends cycle-based assessment into chronic-disease prevention and reproductive endocrinology.</p>"""
},
56: {
"v2": """Cooperative Progesterone Replacement Therapy (CPRT) is the term used in NaProTechnology for cycle-timed luteal-phase progesterone support given alongside ongoing natural ovulation rather than as a contraceptive or cycle-suppressing intervention.[78] The "cooperative" designation reflects that the supplemental progesterone is timed to complement the corpus luteum's own output during the luteal phase, supporting endometrial preparation and early pregnancy maintenance without overriding the patient's underlying cycle physiology.

CPRT is the standard NaProTechnology intervention for documented luteal phase deficiency and for early-pregnancy progesterone support in patients with recurrent pregnancy loss attributable to luteal insufficiency. It is conceptually distinct from continuous progestin administration (as in hormonal contraception) and from intramuscular progesterone protocols used in IVF cycle support. CPRT formulations are isomolecular (chemically identical to endogenous progesterone) rather than synthetic progestins.

The cooperative principle is the operational expression of the broader restorative reproductive medicine framework: rather than replacing or suppressing the corpus luteum's function, CPRT supplements where the corpus luteum's output is insufficient and withdraws when the placenta takes over progesterone production. The specific timing, dosing, and duration are clinical decisions made by a NaProTechnology Medical Consultant in conjunction with the patient's chart and laboratory data.""",
"v2_html": """<p><strong>Cooperative Progesterone Replacement Therapy (CPRT) is the term used in <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> for cycle-timed luteal-phase progesterone support given alongside ongoing natural ovulation rather than as a contraceptive or cycle-suppressing intervention.</strong><sup class="cite-ref"><a href="#ref-78">78</a></sup> The "cooperative" designation reflects that the supplemental progesterone is timed to complement the <a href="#corpus-luteum" class="gloss-xref">corpus luteum</a>'s own output during the luteal phase, supporting endometrial preparation and early pregnancy maintenance without overriding the patient's underlying cycle physiology.</p><p>CPRT is the standard NaProTechnology intervention for documented <a href="#luteal-phase-defect" class="gloss-xref">luteal phase deficiency</a> and for early-pregnancy progesterone support in patients with recurrent pregnancy loss attributable to luteal insufficiency. It is conceptually distinct from continuous progestin administration (as in hormonal contraception) and from intramuscular progesterone protocols used in IVF cycle support. CPRT formulations are isomolecular (chemically identical to endogenous progesterone) rather than synthetic progestins.</p><p>The cooperative principle is the operational expression of the broader <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a> framework: rather than replacing or suppressing the corpus luteum's function, CPRT supplements where the corpus luteum's output is insufficient and withdraws when the placenta takes over progesterone production. The specific timing, dosing, and duration are clinical decisions made by a <a href="#napro-medical-consultant" class="gloss-xref">NaProTechnology Medical Consultant</a> in conjunction with the patient's chart and laboratory data.</p>"""
},
55: {
"v2": """Cooperative Estrogen Replacement Therapy (CERT) is the NaProTechnology term for cycle-timed estradiol supplementation given to correct deficient estrogen output in specific subtypes of luteal phase deficiency and impaired follicular development.[78] It is the sister protocol to Cooperative Progesterone Replacement Therapy (CPRT): both are timed to the patient's natural cycle rather than substituted for it, and both use isomolecular (bioidentical) hormones rather than synthetic analogues.

CERT addresses estradiol-specific deficits identified through cycle charting and laboratory evaluation, particularly the Type V luteal phase defect (an isolated luteal estradiol deficit). Synthetic estrogens used in hormonal contraception (such as ethinyl estradiol) are not used in CERT; CERT exclusively uses 17β-estradiol, chemically identical to endogenous estrogen. This is a deliberate distinction reflecting the restorative principle: CERT supplements where the patient's own estradiol output is insufficient, rather than replacing endogenous regulation with a pharmacologic substitute.

CERT is administered in coordination with CPRT when both estradiol and progesterone deficits are present. The specific dosing, route, and timing are determined by a NaProTechnology Medical Consultant based on the patient's diagnostic data and cycle pattern. CERT is not a standalone treatment for menopause, hormone replacement therapy, or contraception; it is a cycle-timed intervention specific to identified luteal-phase or follicular-phase estrogen deficiency.""",
"v2_html": """<p><strong>Cooperative Estrogen Replacement Therapy (CERT) is the <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> term for cycle-timed estradiol supplementation given to correct deficient estrogen output in specific subtypes of luteal phase deficiency and impaired follicular development.</strong><sup class="cite-ref"><a href="#ref-78">78</a></sup> It is the sister protocol to <a href="#cooperative-progesterone-replacement-therapy" class="gloss-xref">Cooperative Progesterone Replacement Therapy (CPRT)</a>: both are timed to the patient's natural cycle rather than substituted for it, and both use isomolecular (bioidentical) hormones rather than synthetic analogues.</p><p>CERT addresses estradiol-specific deficits identified through cycle charting and laboratory evaluation, particularly the Type V <a href="#luteal-phase-defect" class="gloss-xref">luteal phase defect</a> (an isolated luteal estradiol deficit). Synthetic estrogens used in hormonal contraception (such as ethinyl estradiol) are not used in CERT; CERT exclusively uses 17β-estradiol, chemically identical to endogenous estrogen. This is a deliberate distinction reflecting the <a href="#restorative-as-a-principle" class="gloss-xref">restorative principle</a>: CERT supplements where the patient's own estradiol output is insufficient, rather than replacing endogenous regulation with a pharmacologic substitute.</p><p>CERT is administered in coordination with CPRT when both estradiol and progesterone deficits are present. The specific dosing, route, and timing are determined by a <a href="#napro-medical-consultant" class="gloss-xref">NaProTechnology Medical Consultant</a> based on the patient's diagnostic data and cycle pattern. CERT is not a standalone treatment for menopause, hormone replacement therapy, or contraception; it is a cycle-timed intervention specific to identified luteal-phase or follicular-phase estrogen deficiency.</p>"""
},
312: {
"v2": """Transcervical Catheterization of the Fallopian Tubes (TCFT) is a non-surgical procedure used in NaProTechnology to clear proximal tubal occlusion caused by debris, mucus plugging, or mild fibrotic adhesion.[78] It is performed under fluoroscopic guidance through the cervix and uterine cornu, often in conjunction with selective hysterosalpingography, and aims to restore tubal patency without the surgical morbidity of laparotomy or laparoscopy.

TCFT addresses the subset of tubal infertility caused by proximal occlusion (block at the uterine end of the fallopian tube) rather than distal damage. Distal tubal disease (such as hydrosalpinx or fimbrial damage) is not amenable to TCFT and is addressed by surgical reconstruction. The procedure was developed and refined by Drs. Thomas Hilgers and Patrick Yeung as part of the NaProTechnology surgical curriculum, and is taught to physicians completing NaProTechnology training in selective hysterosalpingography.

TCFT is consistent with the restorative reproductive medicine principle of repairing native anatomy rather than bypassing it. For patients with isolated proximal tubal occlusion, TCFT preserves the option of unassisted conception that in vitro fertilization would forgo. The procedure is not appropriate for every tubal occlusion pattern; selection requires fluoroscopic and clinical assessment by a clinician trained in the technique.""",
"v2_html": """<p><strong>Transcervical Catheterization of the Fallopian Tubes (TCFT) is a non-surgical procedure used in <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> to clear proximal tubal occlusion caused by debris, mucus plugging, or mild fibrotic adhesion.</strong><sup class="cite-ref"><a href="#ref-78">78</a></sup> It is performed under fluoroscopic guidance through the cervix and uterine cornu, often in conjunction with selective hysterosalpingography, and aims to restore tubal patency without the surgical morbidity of laparotomy or laparoscopy.</p><p>TCFT addresses the subset of tubal infertility caused by proximal occlusion (block at the uterine end of the fallopian tube) rather than distal damage. Distal tubal disease (such as hydrosalpinx or fimbrial damage) is not amenable to TCFT and is addressed by surgical reconstruction. The procedure was developed and refined by Drs. Thomas Hilgers and Patrick Yeung as part of the NaProTechnology surgical curriculum, and is taught to physicians completing NaProTechnology training in selective hysterosalpingography.</p><p>TCFT is consistent with the <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a> principle of repairing native anatomy rather than bypassing it. For patients with isolated proximal tubal occlusion, TCFT preserves the option of unassisted conception that <a href="#ivf" class="gloss-xref">in vitro fertilization</a> would forgo. The procedure is not appropriate for every tubal occlusion pattern; selection requires fluoroscopic and clinical assessment by a clinician trained in the technique.</p>"""
},
162: {
"v2": """Laparoscopic Ovarian Wedge Resection (LOWR) is a fertility-restorative surgical procedure for polycystic ovary syndrome in which a V-shaped wedge of androgen-producing ovarian cortex is excised through laparoscopic access, with the aim of reducing ovarian androgen output and restoring spontaneous ovulation.[78] LOWR derives from the original open ovarian wedge resection described by Stein and Leventhal in 1935, adapted to laparoscopic technique to reduce postoperative adhesion formation and operative morbidity.

In NaProTechnology, LOWR is preserved as a valid surgical option for ovulation-resistant PCOS, particularly when medical induction of ovulation has failed or when surgical correction of associated pelvic pathology is undertaken at the same time. The procedure is performed within the broader NARPS framework, with microsurgical handling, judicious hemostasis, and adhesion-prevention principles applied at every step. This stands in contrast to laparoscopic ovarian drilling (LOD), the mainstream alternative, which uses electrocautery or laser punctures rather than excision; LOD is less tissue-conserving in pattern, and outcomes in the restorative reproductive medicine literature continue to favor wedge resection in selected patients.

LOWR is not a first-line treatment for every PCOS presentation; selection depends on documented ovulation resistance, associated pelvic disease, and the patient's broader fertility evaluation. Outcomes vary with patient phenotype, surgical technique, and adherence to NARPS principles.""",
"v2_html": """<p><strong>Laparoscopic Ovarian Wedge Resection (LOWR) is a fertility-restorative surgical procedure for <a href="#pcos" class="gloss-xref">polycystic ovary syndrome</a> in which a V-shaped wedge of androgen-producing ovarian cortex is excised through laparoscopic access, with the aim of reducing ovarian androgen output and restoring spontaneous ovulation.</strong><sup class="cite-ref"><a href="#ref-78">78</a></sup> LOWR derives from the original open ovarian wedge resection described by Stein and Leventhal in 1935, adapted to laparoscopic technique to reduce postoperative adhesion formation and operative morbidity.</p><p>In <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a>, LOWR is preserved as a valid surgical option for ovulation-resistant PCOS, particularly when medical induction of ovulation has failed or when surgical correction of associated pelvic pathology is undertaken at the same time. The procedure is performed within the broader <a href="#near-adhesion-free-reconstructive-pelvic-surgery" class="gloss-xref">NARPS</a> framework, with microsurgical handling, judicious hemostasis, and adhesion-prevention principles applied at every step. This stands in contrast to laparoscopic ovarian drilling (LOD), the mainstream alternative, which uses electrocautery or laser punctures rather than excision; LOD is less tissue-conserving in pattern, and outcomes in the restorative reproductive medicine literature continue to favor wedge resection in selected patients.</p><p>LOWR is not a first-line treatment for every PCOS presentation; selection depends on documented ovulation resistance, associated pelvic disease, and the patient's broader fertility evaluation. Outcomes vary with patient phenotype, surgical technique, and adherence to NARPS principles.</p>"""
},
212: {
"v2": """Natural killer (NK) cells are cytotoxic lymphocytes of the innate immune system that act without prior antigen sensitization, classically targeting transformed and virus-infected cells. In reproductive medicine, two anatomically distinct NK populations are clinically relevant: uterine NK cells (uNK), which dominate the decidual immune environment during early pregnancy and contribute to spiral artery remodeling and placental development, and peripheral blood NK cells (pbNK), which circulate systemically and are functionally and phenotypically distinct from their uterine counterparts.

The clinical role of NK testing in fertility evaluation is contested. Elevated peripheral NK cell cytotoxicity has been proposed as a marker of immunological contribution to recurrent miscarriage, but assay methods are not standardized across laboratories and reference ranges vary. Uterine NK cell assessment requires endometrial biopsy and is performed in research and tertiary settings rather than routine practice. The American Society for Reproductive Medicine considers routine NK testing investigational; some restorative reproductive medicine practitioners include peripheral NK cytotoxicity panels selectively in evaluation of recurrent pregnancy loss when other causes have been excluded.

Therapeutic implications of NK findings remain unsettled. Reported interventions in the recurrent miscarriage literature include corticosteroids, intravenous immunoglobulin, and intralipid infusions, none of which has Level I evidence supporting routine use. In RRM practice, NK testing is best understood as one input within a multi-factor immunological evaluation rather than as a standalone diagnostic for treatment selection.""",
"v2_html": """<p><strong>Natural killer (NK) cells are cytotoxic lymphocytes of the innate immune system that act without prior antigen sensitization, classically targeting transformed and virus-infected cells.</strong> In reproductive medicine, two anatomically distinct NK populations are clinically relevant: <strong>uterine NK cells</strong> (uNK), which dominate the decidual immune environment during early pregnancy and contribute to spiral artery remodeling and placental development, and <strong>peripheral blood NK cells</strong> (pbNK), which circulate systemically and are functionally and phenotypically distinct from their uterine counterparts.</p><p>The clinical role of NK testing in fertility evaluation is contested. Elevated peripheral NK cell cytotoxicity has been proposed as a marker of immunological contribution to <a href="#recurrent-pregnancy-loss" class="gloss-xref">recurrent miscarriage</a>, but assay methods are not standardized across laboratories and reference ranges vary. Uterine NK cell assessment requires endometrial biopsy and is performed in research and tertiary settings rather than routine practice. The American Society for Reproductive Medicine considers routine NK testing investigational; some <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a> practitioners include peripheral NK cytotoxicity panels selectively in evaluation of recurrent pregnancy loss when other causes have been excluded.</p><p>Therapeutic implications of NK findings remain unsettled. Reported interventions in the recurrent miscarriage literature include corticosteroids, intravenous immunoglobulin, and intralipid infusions, none of which has Level I evidence supporting routine use. In RRM practice, NK testing is best understood as one input within a multi-factor immunological evaluation rather than as a standalone diagnostic for treatment selection.</p>"""
},
111: {
"v2": """A FertilityCare Practitioner (FCP) is a trained educator credentialed to instruct individuals and couples in the Creighton Model FertilityCare System.[64] FCPs are not physicians; they hold a non-clinical credential focused on teaching standardized cycle observation, charting, and chart review according to the Creighton Model protocol. Most FCPs complete a postgraduate certification program (commonly through FertilityCare Centers of America) that includes both didactic coursework and supervised teaching practicum.

In the NaProTechnology care model, the FCP is the entry point. A patient begins with an FCP-supervised introductory session, learns the standardized observation protocol, and produces a chart that becomes the primary clinical document for subsequent NaProTechnology Medical Consultant evaluation. The FCP's role is continuous: ongoing follow-up sessions ensure observation accuracy, address charting questions, and identify when a chart pattern warrants clinical referral.

FCPs do not diagnose, prescribe, or perform clinical procedures. Their role is educational and the chart is the clinical artifact they produce. The integrity of the entire NaProTechnology diagnostic and therapeutic process depends on accurate, reproducible charts produced under FCP supervision; without a reliable chart, the cycle-timed laboratory and ultrasound investigations that follow lose their interpretive frame. The FCP credential is distinct from physician credentials in NaProTechnology (the Medical Consultant), and the two work cooperatively rather than substitutably.""",
"v2_html": """<p><strong>A FertilityCare Practitioner (FCP) is a trained educator credentialed to instruct individuals and couples in the <a href="#creighton-model" class="gloss-xref">Creighton Model FertilityCare System</a>.</strong><sup class="cite-ref"><a href="#ref-64">64</a></sup> FCPs are not physicians; they hold a non-clinical credential focused on teaching standardized cycle observation, charting, and chart review according to the Creighton Model protocol. Most FCPs complete a postgraduate certification program (commonly through FertilityCare Centers of America) that includes both didactic coursework and supervised teaching practicum.</p><p>In the <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> care model, the FCP is the entry point. A patient begins with an FCP-supervised introductory session, learns the standardized observation protocol, and produces a chart that becomes the primary clinical document for subsequent <a href="#napro-medical-consultant" class="gloss-xref">NaProTechnology Medical Consultant</a> evaluation. The FCP's role is continuous: ongoing follow-up sessions ensure observation accuracy, address charting questions, and identify when a chart pattern warrants clinical referral.</p><p>FCPs do not diagnose, prescribe, or perform clinical procedures. Their role is educational and the chart is the clinical artifact they produce. The integrity of the entire NaProTechnology diagnostic and therapeutic process depends on accurate, reproducible charts produced under FCP supervision; without a reliable chart, the cycle-timed laboratory and ultrasound investigations that follow lose their interpretive frame. The FCP credential is distinct from physician credentials in NaProTechnology (the Medical Consultant), and the two work cooperatively rather than substitutably.</p>"""
},
206: {
"v2": """A NaProTechnology Medical Consultant (commonly abbreviated NFPMC or NaPro MC) is a physician (MD or DO) who has completed formal postgraduate training in NaProTechnology and works cooperatively with the patient's FertilityCare Practitioner-produced chart to diagnose and treat reproductive disorders.[64] Training routes include the fellowship at the Pope Paul VI Institute for the Study of Human Reproduction and the Medical Consultant certification offered by the American Academy of FertilityCare Professionals; both pathways add NaProTechnology competency to existing physician credentials rather than replacing them.

The Medical Consultant's distinctive expertise is integrating cycle chart interpretation with cycle-timed laboratory and ultrasound investigations, with the broader cycle pattern guiding diagnostic and therapeutic decisions. This contrasts with the standard reproductive medicine workflow, in which the patient's cycle observations are not part of the clinical record and diagnostic testing is timed by calendar date or LH-detection rather than charted biomarkers. NaProTechnology Medical Consultants commonly hold concurrent credentials in obstetrics-gynecology, family medicine, or reproductive endocrinology, and the NaProTechnology training augments rather than replaces those base specialties.

The Medical Consultant role is collaborative with the FertilityCare Practitioner and, where surgical management is indicated, with surgeons trained in NaProTechnology surgical techniques (PEARS, NARPS). The credential signals a clinician who has been trained to read the cycle chart as primary clinical data and to treat reproductive disorders through restorative interventions rather than suppressive or bypass alternatives.""",
"v2_html": """<p><strong>A NaProTechnology Medical Consultant (commonly abbreviated NFPMC or NaPro MC) is a physician (MD or DO) who has completed formal postgraduate training in <a href="#naprotechnology-definition" class="gloss-xref">NaProTechnology</a> and works cooperatively with the patient's <a href="#fertilitycare-practitioner" class="gloss-xref">FertilityCare Practitioner</a>-produced chart to diagnose and treat reproductive disorders.</strong><sup class="cite-ref"><a href="#ref-64">64</a></sup> Training routes include the fellowship at the Pope Paul VI Institute for the Study of Human Reproduction and the Medical Consultant certification offered by the American Academy of FertilityCare Professionals; both pathways add NaProTechnology competency to existing physician credentials rather than replacing them.</p><p>The Medical Consultant's distinctive expertise is integrating cycle chart interpretation with cycle-timed laboratory and ultrasound investigations, with the broader cycle pattern guiding diagnostic and therapeutic decisions. This contrasts with the standard reproductive medicine workflow, in which the patient's cycle observations are not part of the clinical record and diagnostic testing is timed by calendar date or LH-detection rather than charted biomarkers. NaProTechnology Medical Consultants commonly hold concurrent credentials in obstetrics-gynecology, family medicine, or reproductive endocrinology, and the NaProTechnology training augments rather than replaces those base specialties.</p><p>The Medical Consultant role is collaborative with the FertilityCare Practitioner and, where surgical management is indicated, with surgeons trained in NaProTechnology surgical techniques (<a href="#pears" class="gloss-xref">PEARS</a>, <a href="#near-adhesion-free-reconstructive-pelvic-surgery" class="gloss-xref">NARPS</a>). The credential signals a clinician who has been trained to read the cycle chart as primary clinical data and to treat reproductive disorders through restorative interventions rather than suppressive or bypass alternatives.</p>"""
},
224: {
"v2": """Oral contraceptives (OCs) are hormone-based pills taken by mouth with the primary clinical purpose of preventing pregnancy. Combined oral contraceptives (COCs) contain a synthetic estrogen (most commonly ethinyl estradiol) plus a synthetic progestin; progestin-only pills contain progestin alone. Both formulations act primarily by suppressing hypothalamic-pituitary release of luteinizing hormone and follicle-stimulating hormone, thereby preventing ovulation, with secondary effects on cervical mucus, the endometrium, and tubal transport.

In addition to contraception, OCs are widely prescribed off-label as symptomatic management for menstrual irregularity, dysmenorrhea, premenstrual symptoms, polycystic ovary syndrome, and endometriosis. In each of these uses, the mechanism is the same as in contraception: suppression of ovulation and induction of a withdrawal bleed substituted for the natural menstrual cycle. Symptomatic improvement reflects suppression of the underlying cycle, not correction of the underlying pathology.

In restorative reproductive medicine, OCs are not used to treat cycle disorders or fertility-related conditions because suppression of the cycle precludes the diagnostic and therapeutic engagement of the underlying pathology. A patient on OCs cannot be evaluated for ovulation timing, luteal phase adequacy, or follicular development; her cycle has been replaced by a pharmacologic synthetic. When patients present on OCs with reproductive complaints, the restorative approach is to discontinue the OC, allow the natural cycle to resume, and then evaluate and treat the underlying condition rather than re-suppress symptoms.""",
"v2_html": """<p><strong>Oral contraceptives (OCs) are hormone-based pills taken by mouth with the primary clinical purpose of preventing pregnancy.</strong> Combined oral contraceptives (COCs) contain a synthetic estrogen (most commonly ethinyl estradiol) plus a synthetic progestin; progestin-only pills contain progestin alone. Both formulations act primarily by suppressing hypothalamic-pituitary release of luteinizing hormone and follicle-stimulating hormone, thereby preventing ovulation, with secondary effects on cervical mucus, the endometrium, and tubal transport.</p><p>In addition to contraception, OCs are widely prescribed off-label as symptomatic management for menstrual irregularity, dysmenorrhea, premenstrual symptoms, <a href="#pcos" class="gloss-xref">polycystic ovary syndrome</a>, and <a href="#endometriosis" class="gloss-xref">endometriosis</a>. In each of these uses, the mechanism is the same as in contraception: suppression of ovulation and induction of a withdrawal bleed substituted for the natural menstrual cycle. Symptomatic improvement reflects suppression of the underlying cycle, not correction of the underlying pathology.</p><p>In <a href="#restorative-reproductive-medicine" class="gloss-xref">restorative reproductive medicine</a>, OCs are not used to treat cycle disorders or fertility-related conditions because suppression of the cycle precludes the diagnostic and therapeutic engagement of the underlying pathology. A patient on OCs cannot be evaluated for ovulation timing, luteal phase adequacy, or follicular development; her cycle has been replaced by a pharmacologic synthetic. When patients present on OCs with reproductive complaints, the restorative approach is to discontinue the OC, allow the natural cycle to resume, and then evaluate and treat the underlying condition rather than re-suppress symptoms.</p>"""
},
}

# Belt-and-suspenders US-English scan
import re
british_patterns = [
    (r'\bminimised\b', 'minimized'), (r'\bminimising\b', 'minimizing'), (r'\bminimise\b', 'minimize'),
    (r'\bharmonised\b', 'harmonized'), (r'\bharmonise\b', 'harmonize'),
    (r'\bformalising\b', 'formalizing'), (r'\bformalised\b', 'formalized'),
    (r'\bpractising\b', 'practicing'), (r'\bspecialised\b', 'specialized'),
    (r'\borganised\b', 'organized'), (r'\borganise\b', 'organize'),
    (r'\bgynaecologic\b', 'gynecologic'), (r'\bhaemostasis\b', 'hemostasis'),
    (r'\boestrogen\b', 'estrogen'), (r'\boedema\b', 'edema'),
    (r'\banaesthesia\b', 'anesthesia'), (r'\bbehaviour\b', 'behavior'),
    (r'\bfavour\b', 'favor'), (r'\bcolour\b', 'color'), (r'\bhonour\b', 'honor'),
    (r'\blabour\b', 'labor'), (r'\bcentre\b', 'center'),
]
def to_us(s):
    placeholder = '___UK_CIO_PROPER_NOUN___'
    s = s.replace('UK Charitable Incorporated Organisation', placeholder)
    for pat, repl in british_patterns:
        s = re.sub(pat, repl, s)
    s = s.replace(placeholder, 'UK Charitable Incorporated Organisation')
    return s

for r in DRAFTS:
    DRAFTS[r]['v2'] = to_us(DRAFTS[r]['v2'])
    DRAFTS[r]['v2_html'] = to_us(DRAFTS[r]['v2_html'])

# Verify no em dashes
em_dash_offenders = []
for r in DRAFTS:
    for col in ('v2', 'v2_html'):
        if '—' in DRAFTS[r][col] or '–' in DRAFTS[r][col]:
            em_dash_offenders.append((r, col))
if em_dash_offenders:
    print("ERROR: em-dash or en-dash found in:")
    for r, c in em_dash_offenders: print(f"  row {r} col {c}")
    raise SystemExit(1)
print("✓ No em-dashes / en-dashes")

# Write to Sheet
def sheets(method, path, body=None):
    url = f"https://sheets.googleapis.com/v4/spreadsheets/{SHEET_ID}{path}"
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {TOKEN}")
    req.add_header("x-goog-user-project", "rrm-academy")
    if data: req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req) as r:
        body = r.read().decode()
        return json.loads(body) if body else {}

batch = []
for r, d in DRAFTS.items():
    batch.append({"range": f"Glossary!AJ{r}:AK{r}", "values":[[d["v2"], d["v2_html"]]]})
    batch.append({"range": f"Glossary!AP{r}:AP{r}", "values":[[f"DRAFT v2 (build-1) {TS} - Part I-VIII v2-build batch"]]})
result = sheets("POST", "/values:batchUpdate", {"valueInputOption":"RAW", "data": batch})
print(f"Wrote {result.get('totalUpdatedCells')} cells across {len(DRAFTS)} rows.")
print(f"Rows: {sorted(DRAFTS.keys())}")
