-- DEPRECATED 2026-05-19 -- DO NOT RUN THIS FILE.
--
-- This file's original ALTER TABLE on articles aborted the whole file with
-- "duplicate column name" because `articles.word_count` already exists in the
-- canonical rrm-cli schema (d1-library.sql:71, added 2026-03-23). wrangler's
-- per-file abort semantics meant the glossary half never executed.
--
-- Split into per-database files instead:
--
--   wrangler d1 execute rrm-library --remote \
--     --file=scripts/migrations/2026-05-19-word-count-rrm-library.sql
--
--   wrangler d1 execute rrm-auth --remote \
--     --file=scripts/migrations/2026-05-19-word-count-rrm-auth.sql
--
-- This file is intentionally a no-op (only this comment block remains) so
-- running it accidentally produces no errors and no schema changes.
