#!/usr/bin/env node
/**
 * Orchestrator: runs coverage → complexity/CRAP → mutation → deps in order,
 * then regenerates docs/quality/BASELINE.md from the produced reports.
 *
 * Tolerates any one tool failing: emits a "⚠ tool failed" note in the
 * baseline doc for that section rather than blocking the whole run.
 *
 * Usage: node scripts/quality/dashboard.mjs
 *        node scripts/quality/dashboard.mjs --skip-mutation  (faster iteration)
 */
import { execSync } from 'node:child_process';
import { mkdir, readFile, writeFile, access } from 'node:fs/promises';
import { resolve, relative } from 'node:path';
import { loadCoverage } from './lib/load-coverage.mjs';
import { mdTable, fmt, pct } from './lib/render-markdown.mjs';

const ROOT = resolve(import.meta.dirname, '..', '..');
const OUT = resolve(ROOT, 'docs', 'quality', 'BASELINE.md');

const skipMutation = process.argv.includes('--skip-mutation');

function run(label, cmd) {
  try {
    console.log(`\n=== ${label} ===`);
    execSync(cmd, { cwd: ROOT, stdio: 'inherit' });
    return true;
  } catch (err) {
    console.error(`[${label}] failed:`, err.message);
    return false;
  }
}

// 1. Coverage
run('coverage', 'node scripts/quality/coverage.mjs');

// 2. CRAP (needs coverage + runs ESLint internally)
run('crap', 'node scripts/quality/crap.mjs');

// 3. Mutation (slow; opt out with --skip-mutation)
if (!skipMutation) {
  run('mutation', 'node scripts/quality/mutation.mjs');
}

// 4. Deps
run('deps', 'node scripts/quality/deps.mjs');

// --- Assemble BASELINE.md ---
await mkdir(resolve(ROOT, 'docs', 'quality'), { recursive: true });

function gitSha() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim();
  } catch { return 'unknown'; }
}

async function tryRead(path) {
  try { await access(path); return await readFile(path, 'utf8'); }
  catch { return null; }
}

async function tryReadJson(path) {
  const s = await tryRead(path);
  if (!s) return null;
  try { return JSON.parse(s); } catch { return null; }
}

const covReport = await tryReadJson(resolve(ROOT, 'reports/quality/coverage/coverage-final.json'));
const crapReport = await tryReadJson(resolve(ROOT, 'reports/quality/crap.json'));
const mutReport = await tryReadJson(resolve(ROOT, 'reports/quality/mutation/mutation.json'));
const depsReport = await tryReadJson(resolve(ROOT, 'reports/quality/deps.json'));

const lines = [];
lines.push('<!-- generated by scripts/quality/dashboard.mjs — do not hand-edit -->');
lines.push('# Quality Baseline — `src/lib/`');
lines.push('');
lines.push('_Snapshot of coverage, mutation score, CRAP, and dependency rules for `src/lib/` as of this commit._');
lines.push('');

// --- Summary per file ---
lines.push('## Summary per file');
lines.push('');
if (!covReport || !crapReport) {
  lines.push('⚠ Coverage or CRAP report missing — summary skipped.');
} else {
  const byFile = {};
  const coverageByFile = await loadCoverage();
  for (const [absPath, entries] of Object.entries(coverageByFile)) {
    const rel = relative(ROOT, absPath);
    const total = entries.length;
    // Filter synthetic empty-report entries before averaging
    const real = entries.filter(e => e.name !== '(empty-report)');
    const isUntouched = total === 1 && entries[0]?.name === '(empty-report)';
    const avgCov = isUntouched ? 0 : (real.length === 0 ? 1 : real.reduce((s, e) => s + e.coverage, 0) / real.length);
    byFile[rel] = { coverage: avgCov, fns: real.length };
  }
  const maxCrapByFile = {};
  for (const r of crapReport.records) {
    maxCrapByFile[r.file] = Math.max(maxCrapByFile[r.file] ?? 0, r.crap);
  }
  const mutByFile = {};
  if (mutReport?.files) {
    for (const [p, data] of Object.entries(mutReport.files)) {
      const total = (data.mutants ?? []).length;
      const killed = (data.mutants ?? []).filter(m => m.status === 'Killed').length;
      mutByFile[relative(ROOT, p)] = total === 0 ? null : killed / total;
    }
  }

  const allFiles = new Set([...Object.keys(byFile), ...Object.keys(maxCrapByFile), ...Object.keys(mutByFile)]);
  const rows = [...allFiles].sort().map(f => [
    f,
    byFile[f] ? pct(byFile[f].coverage) : '—',
    mutByFile[f] == null ? '—' : pct(mutByFile[f]),
    maxCrapByFile[f] == null ? '—' : fmt(maxCrapByFile[f], 1),
  ]);
  lines.push(mdTable(['File', 'Line cov', 'Mutation', 'Max CRAP'], rows));
}
lines.push('');

// --- CRAP red band ---
lines.push('## CRAP danger band (>30)');
lines.push('');
if (!crapReport) {
  lines.push('⚠ CRAP report missing.');
} else {
  const danger = crapReport.records.filter(r => r.band === 'danger');
  if (danger.length === 0) {
    lines.push('_None — every function is within acceptable bounds._');
  } else {
    lines.push(mdTable(
      ['File', 'Function', 'Line', 'CC', 'Cov', 'CRAP'],
      danger.map(r => [r.file, r.name, r.line, r.complexity, pct(r.coverage), fmt(r.crap, 1)]),
    ));
  }
}
lines.push('');

// --- Coverage gaps ---
lines.push('## Coverage gaps (<50%)');
lines.push('');
if (!covReport) {
  lines.push('⚠ Coverage report missing.');
} else {
  const coverageByFile = await loadCoverage();
  const gaps = Object.entries(coverageByFile)
    .map(([p, entries]) => {
      const real = entries.filter(e => e.name !== '(empty-report)');
      const isUntouched = entries.length === 1 && entries[0]?.name === '(empty-report)';
      const avg = isUntouched ? 0 : (real.length === 0 ? 1 : real.reduce((s, e) => s + e.coverage, 0) / real.length);
      return { file: relative(ROOT, p), coverage: avg };
    })
    .filter(x => x.coverage < 0.5)
    .sort((a, b) => {
      if (a.coverage !== b.coverage) return a.coverage - b.coverage;
      return a.file < b.file ? -1 : 1;
    });
  lines.push(gaps.length === 0
    ? '_All files above 50% coverage._'
    : mdTable(['File', 'Coverage'], gaps.map(g => [g.file, pct(g.coverage)])));
}
lines.push('');

// --- Mutation survivors (top 20) ---
lines.push('## Top 20 surviving mutants');
lines.push('');
const timedOutMarker = await tryRead(resolve(ROOT, 'reports/quality/mutation/TIMED_OUT'));
if (timedOutMarker) {
  lines.push(`⚠ Mutation run timed out. ${timedOutMarker.trim()}`);
} else if (!mutReport) {
  lines.push(skipMutation ? '_Skipped (--skip-mutation)._' : '⚠ Mutation report missing.');
} else {
  const survivors = [];
  for (const [p, data] of Object.entries(mutReport.files ?? {})) {
    for (const m of data.mutants ?? []) {
      if (m.status === 'Survived') {
        survivors.push({
          file: relative(ROOT, p),
          line: m.location?.start?.line ?? '—',
          mutator: m.mutatorName,
          replacement: (m.replacement ?? '').slice(0, 60),
        });
      }
    }
  }
  survivors.sort((a, b) => {
    if (a.file !== b.file) return a.file < b.file ? -1 : 1;
    return a.line - b.line;
  });
  const top20 = survivors.slice(0, 20);
  lines.push(top20.length === 0
    ? '_No survivors._'
    : mdTable(['File', 'Line', 'Mutator', 'Replacement'], top20.map(s => [s.file, s.line, s.mutator, '`' + s.replacement + '`'])));
}
lines.push('');

// --- Dependency violations ---
lines.push('## Dependency violations');
lines.push('');
if (!depsReport) {
  lines.push('⚠ Deps report missing.');
} else {
  const vs = depsReport.summary?.violations ?? [];
  // Deterministic order: severity desc, then rule asc, then from asc, then to asc
  const sorted = [...vs].sort((a, b) => {
    const sa = a.rule?.severity ?? '';
    const sb = b.rule?.severity ?? '';
    if (sa !== sb) return sa < sb ? -1 : 1;
    const ra = a.rule?.name ?? '';
    const rb = b.rule?.name ?? '';
    if (ra !== rb) return ra < rb ? -1 : 1;
    if (a.from !== b.from) return a.from < b.from ? -1 : 1;
    return (a.to ?? '') < (b.to ?? '') ? -1 : 1;
  });
  lines.push(sorted.length === 0
    ? '_None._'
    : mdTable(['Rule', 'Severity', 'From', 'To'],
        sorted.map(v => [v.rule?.name ?? '?', v.rule?.severity ?? '?', v.from, v.to])));
}
lines.push('');

// --- Footer ---
lines.push('---');
lines.push('');
lines.push(`**Generated:** ${new Date().toISOString()}  `);
lines.push(`**Commit:** \`${gitSha()}\``);
lines.push('');

await writeFile(OUT, lines.join('\n'));
console.log(`\n[dashboard] wrote ${OUT}`);
