#!/usr/bin/env node
/**
 * check-kit -- the consumer-side half of console-kit's drift gate.
 *
 * Runs FIRST inside `npm run verify`, needs nothing but this repo: it compares
 * every file kit.lock.json records against the sha the last `console-kit sync`
 * wrote, and goes red BY NAME on any mismatch or absence. It cannot tell you
 * the kit has moved on (only `console-kit check`, run from the kit repo, can);
 * what it proves is that nobody has locally edited a vendored file since the
 * last sync -- which is exactly the silent failure that let two consoles carry
 * eight byte-identical files with nothing holding them identical.
 *
 * A red here has exactly two honest exits: revert the local edit, or make the
 * change IN THE KIT and re-sync. Editing kit.lock.json by hand to match a
 * local edit is the failure mode this file exists to make loud, so do not.
 *
 * GENERATED-class entries (kit.lock.json's `generated` map: path -> generator
 * name) are the one exception to "compare bytes to the recorded sha". Their
 * bytes are supposed to change whenever console.config.mjs changes, so a
 * static sha comparison is blind to a config-only edit that changes a
 * generator's OUTPUT: harmless in kit 0.1.0 (canonicalHost only reaches
 * comment lines) but structural -- the first generator whose output depends
 * on config would drift silently through every CI run (/arise 2026-08-24
 * finding #7). So for those paths this file re-renders from the consumer's
 * own console.config.mjs and compares against THAT, the same way
 * `console-kit check` (run from the kit repo) already does. The GENERATORS
 * below MIRROR bin/console-kit's exactly -- this file has no access to the
 * kit repo by design (it is the vendored, zero-dependency half that ships
 * INTO consumers); keep both copies byte-identical whenever a generator
 * changes, the same discipline that keeps every other vendored file in sync.
 *
 * PACKAGES (kit.lock.json `packages`) are checked the same way as files: they
 * are the estate-shared modules this consumer vendored under `vendor/<name>/`,
 * and one consumer editing its local copy is exactly what having one verifier
 * and one mail sender is supposed to prevent.
 *
 * Zero dependencies (console.config.mjs is loaded via a plain dynamic
 * `import()` of a file already required to exist in every kit consumer, not
 * an installed package). Exit 0 clean, 1 on any drift, 2 on a missing/
 * unreadable lock (a consumer without a lock is not a kit consumer; run
 * console-kit sync).
 */

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** MUST mirror bin/console-kit's GENERATORS object. See header comment. */
const GENERATORS = {
  /**
   * public/_headers. ONE block, ever: the house rule is one block per path
   * pattern (~/iCode/docs/standards/cf-pages-headers-pattern.md), because a
   * second block for the same pattern replaces rather than merges and would
   * silently drop x-robots-tag and the rest.
   *
   * The Content-Security-Policy is a LINE inside that block, rendered from
   * cfg.securityHeaders.contentSecurityPolicy when the consumer declares one.
   * `reportOnly: true` renders Content-Security-Policy-Report-Only instead, so
   * a console can measure its real script-src on a preview before enforcing.
   */
  headers(cfg) {
    const lines = [
      '# One block per path pattern (house rule: docs/standards/cf-pages-headers-pattern.md).',
      `# Internal console on ${cfg.canonicalHost} behind Cloudflare Access: never indexed,`,
      '# never framed. The static export copies public/ into out/ and Pages serves',
      '# out/_headers. Verify on the LIVE host after deploy, not in this file:',
      `#   curl -sI https://${cfg.canonicalHost}/ | grep -i x-robots-tag`,
      '# GENERATED by console-kit from console.config.mjs -- edit the config, not this file.',
      '/*',
      '  X-Robots-Tag: noindex, nofollow',
      '  X-Content-Type-Options: nosniff',
      '  X-Frame-Options: DENY',
      '  Referrer-Policy: same-origin',
    ];
    const csp = cfg.securityHeaders && cfg.securityHeaders.contentSecurityPolicy;
    if (csp) {
      const directives = csp.directives || {};
      const names = Object.keys(directives);
      if (names.length === 0) throw new Error('headers generator: securityHeaders.contentSecurityPolicy declares no directives (a policy with nothing in it is a header that permits everything)');
      const rendered = names.map((name) => {
        const value = directives[name];
        // Both halves land verbatim in a served header, so constrain them
        // here rather than trusting the config: a newline would end the
        // header line early and everything after it would be dropped, and a
        // stray ';' would smuggle in a directive no reader of the config sees.
        if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error(`headers generator: '${name}' is not a CSP directive name`);
        if (typeof value !== 'string' || !value) throw new Error(`headers generator: directive '${name}' has no value`);
        if (/[\x00-\x1f\x7f;]/.test(value)) throw new Error(`headers generator: directive '${name}' value contains a control character or ';' -- one directive per key`);
        return `${name} ${value}`;
      }).join('; ');
      const header = csp.reportOnly ? 'Content-Security-Policy-Report-Only' : 'Content-Security-Policy';
      const line = `  ${header}: ${rendered}`;
      // Cloudflare Pages silently drops any _headers line over roughly 1980
      // characters and serves the response with no such header at all: no
      // deploy error, no warning (memory cf-pages-headers-line-length-limit,
      // found the hard way on fsp-dashboard 2026-09-02). Fail here instead.
      if (line.length > 1900) throw new Error(`headers generator: the ${header} line is ${line.length} characters; Cloudflare Pages silently drops a _headers line over ~1980`);
      lines.push(line);
    }
    lines.push('');
    return lines.join('\n');
  },
  robots() {
    return 'User-agent: *\nDisallow: /\n';
  },
  middleware(cfg) {
    const legacyHosts = Array.isArray(cfg.legacyHosts)
      ? cfg.legacyHosts
      : cfg.legacyHost
        ? [cfg.legacyHost]
        : [];
    if (!cfg.canonicalHost || typeof cfg.canonicalHost !== 'string') {
      throw new Error('middleware generator requires cfg.canonicalHost');
    }
    if (legacyHosts.length === 0) {
      throw new Error('middleware generator requires cfg.legacyHosts (non-empty array, or the singular cfg.legacyHost) when features.legacyHostRedirect is enabled');
    }
    const hostsLiteral = legacyHosts.map((h) => JSON.stringify(h)).join(', ');
    return [
      '/**',
      ' * functions/_middleware.js -- the canonical-host redirect, and nothing else.',
      ' *',
      ' * GENERATED by console-kit from console.config.mjs (canonicalHost, legacyHosts',
      ' * / legacyHost) -- edit the config, not this file.',
      ' *',
      ` * ${cfg.canonicalHost} is this console's canonical host. Every host in`,
      ' * LEGACY_HOSTS below answers but is sent here with a 308, never a 301 (a 301',
      ' * lets a client rewrite a POST into a GET on the way; RFC 9110 permits it and',
      ' * clients do it).',
      ' *',
      ' * IT REDIRECTS THE SITE AND NOT THE API. A machine caller that pins a legacy',
      " * host in an API URL and treats any 3xx as failure (so it never reads an",
      ' * Access login page\'s 200 HTML as success) would break if /api were',
      ' * redirected -- audit for callers like that before enabling this flag on a',
      ' * consumer with existing machine integrations. `/api` and `/api/*` therefore',
      ' * answer, unchanged, on every attached hostname; the match below is an exact',
      ' * segment test, not startsWith, so a future page at /apidocs is a PAGE and',
      ' * gets redirected like one.',
      ' *',
      ' * ONLY BARE, EXACTLY-NAMED HOSTS ARE SENT AWAY. A Pages preview answers on',
      " * `<hash>.<project>.pages.dev`, and a preview's whole purpose is to be looked",
      ' * at on its own hostname before it becomes production -- redirecting it to the',
      ' * live build would make a broken preview look identical to production, the',
      ' * hardest failure to notice. The match is an equality against each literal',
      ' * string below, never a suffix / .endsWith() test.',
      ' *',
      ' * THIS RUNS AFTER CLOUDFLARE ACCESS: an unauthenticated request to a legacy',
      ' * host meets the Access login first and only reaches this code holding a',
      ' * session. The redirect is a canonicalisation, never a security control.',
      ' */',
      '',
      `const CANONICAL_HOST = ${JSON.stringify(cfg.canonicalHost)};`,
      '',
      '/**',
      ' * Every host that answers but should not. Membership is by EXACT string,',
      ' * never by suffix -- see the header for why a suffix match would be invisible.',
      ' */',
      `const LEGACY_HOSTS = new Set([${hostsLiteral}]);`,
      '',
      '/**',
      ' * True for the API surface, which answers on EVERY attached hostname,',
      ' * retired or not. Written as an exact-segment test rather than',
      " * startsWith('/api') so that a future page at /apidocs is a PAGE and gets",
      ' * redirected like one.',
      ' */',
      'function isApiPath(pathname) {',
      "  return pathname === '/api' || pathname.startsWith('/api/');",
      '}',
      '',
      'export function onRequest(context) {',
      '  const url = new URL(context.request.url);',
      '  if (!LEGACY_HOSTS.has(url.hostname)) return context.next();',
      '  if (isApiPath(url.pathname)) return context.next();',
      '',
      '  // Path, query and hash ride along, so a bookmarked deep link -- and every',
      '  // signing or prefill link an operator ever pasted somewhere -- lands on',
      '  // the same screen it used to.',
      '  url.hostname = CANONICAL_HOST;',
      '  return Response.redirect(url.toString(), 308);',
      '}',
      '',
    ].join('\n');
  },
};

let lock;
try {
  lock = JSON.parse(readFileSync(resolve(ROOT, 'kit.lock.json'), 'utf8'));
} catch (err) {
  console.error(`check-kit: cannot read kit.lock.json (${err.code || err.message}); run console-kit sync from the kit repo.`);
  process.exit(2);
}

const files = lock.files || {};
const generated = lock.generated || {};
const paths = Object.keys(files).sort();

// Counted across BOTH halves of the lock: a consumer that vendors only shared
// packages and no console files (a worker, an Astro site) still has a gate that
// can fail, and must not be told its lock is empty.
const lockedPackageFileCount = Object.values(lock.packages || {})
  .reduce((n, record) => n + Object.keys((record && record.files) || {}).length, 0);
if (paths.length === 0 && lockedPackageFileCount === 0) {
  console.error('check-kit: kit.lock.json records no files; a lock with nothing to hold is a gate that cannot fail.');
  process.exit(2);
}

let cfg = null;
if (Object.keys(generated).length > 0) {
  try {
    const mod = await import(pathToFileURL(resolve(ROOT, 'console.config.mjs')).href);
    cfg = mod.default;
  } catch (err) {
    console.error(`check-kit: kit.lock.json records generated file(s) but console.config.mjs could not be loaded (${err.message}).`);
    process.exit(2);
  }
}

let bad = 0;

for (const path of paths) {
  let actualSha;
  try {
    actualSha = createHash('sha256').update(readFileSync(resolve(ROOT, path))).digest('hex');
  } catch {
    console.error(`check-kit: MISSING  ${path} (locked but absent)`);
    bad += 1;
    continue;
  }

  const generatorName = generated[path];
  if (!generatorName) {
    if (actualSha !== files[path]) {
      console.error(`check-kit: DRIFT    ${path} (locally edited since the last sync; fix it in the kit, or revert)`);
      bad += 1;
    }
    continue;
  }

  const generator = GENERATORS[generatorName];
  if (!generator) {
    console.error(`check-kit: ${path} is recorded as generated by '${generatorName}', which this check-kit.mjs does not know how to render (kit/consumer version mismatch -- re-sync)`);
    bad += 1;
    continue;
  }
  let expectedSha;
  try {
    expectedSha = createHash('sha256').update(Buffer.from(generator(cfg))).digest('hex');
  } catch (err) {
    console.error(`check-kit: ${path} could not be re-rendered from console.config.mjs (${err.message})`);
    bad += 1;
    continue;
  }
  if (actualSha !== expectedSha) {
    console.error(`check-kit: DRIFT    ${path} (does not match what console.config.mjs would render -- edit the config and re-sync)`);
    bad += 1;
  }
}

/**
 * Packages (kit.lock.json `packages`: name -> { version, files }) are the
 * estate-shared modules this consumer opted into with `packages: [...]` in
 * console.config.mjs, vendored under `vendor/<name>/`. They are sha-enforced
 * exactly like an infra file, and for the same reason: the whole point of one
 * Access verifier and one mail sender is that a fix in the kit reaches every
 * consumer, which is only true while nobody has quietly edited a local copy.
 * Never generated, so they are a straight byte comparison.
 */
let packageFileCount = 0;
for (const [name, record] of Object.entries(lock.packages || {})) {
  for (const [rel, expectedSha] of Object.entries((record && record.files) || {})) {
    const path = `vendor/${name}/${rel}`;
    packageFileCount += 1;
    let actualSha;
    try {
      actualSha = createHash('sha256').update(readFileSync(resolve(ROOT, path))).digest('hex');
    } catch {
      console.error(`check-kit: MISSING  ${path} (locked but absent)`);
      bad += 1;
      continue;
    }
    if (actualSha !== expectedSha) {
      console.error(`check-kit: DRIFT    ${path} (package ${name}@${record.version || '?'} locally edited since the last sync; fix it in the kit, or revert)`);
      bad += 1;
    }
  }
}

if (bad === 0) {
  console.log(`check-kit: OK -- ${paths.length} vendored file(s)${packageFileCount ? ` + ${packageFileCount} package file(s)` : ''} match kit.lock.json (kit ${lock.kitVersion || '?'})`);
  process.exit(0);
}

console.error(`check-kit: ${bad} file(s) drifted from kit.lock.json (kit ${lock.kitVersion || '?'})`);
process.exit(1);
